// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evpvipbteuavhshsnodk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2cHZpcGJ0ZXVhdmhzaHNub2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNjA0MjIsImV4cCI6MjA2NjYzNjQyMn0.2iIqs3N6-Hx3dzgE04aWCqGyHpZyAe4VtAolR_WRpSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);